version: "3"

vars:
  COVERAGE_DIR: .coverage
  IMAGE_NAME: go-service-template-v2

tasks:
  run:
    desc: "Run the server (usage: task run PROFILE=local)"
    requires:
      vars: [PROFILE]
    env:
      APP_PROFILE: "{{.PROFILE}}"
    cmds:
      - go run ./cmd/server/

  dev:
    desc: Start development server with hot reload
    env:
      APP_PROFILE: local
    cmds:
      - go tool air

  test:
    desc: Run unit tests with testdox output
    cmds:
      - go tool gotestsum --format testdox -- ./...

  lint:
    desc: Run golangci-lint
    cmds:
      - go tool golangci-lint run ./...

  build:
    desc: Build the server binary
    cmds:
      - go build -o bin/server ./cmd/server/

  mocks:
    desc: Generate mocks with mockery
    cmds:
      - go tool mockery

  deadcode:
    desc: Detect dead code
    cmds:
      - go tool deadcode ./...

  coverage:
    desc: Run tests with coverage report
    cmds:
      - mkdir -p {{.COVERAGE_DIR}}
      - go tool gotestsum --format testdox -- -coverprofile={{.COVERAGE_DIR}}/coverage.out -covermode=atomic ./...
      - go tool cover -html={{.COVERAGE_DIR}}/coverage.out -o {{.COVERAGE_DIR}}/coverage.html
      - go tool cover -func={{.COVERAGE_DIR}}/coverage.out

  vuln:
    desc: Run vulnerability check
    cmds:
      - go tool govulncheck ./...

  docker:build:
    desc: Build the Docker image
    cmds:
      - docker build -t {{.IMAGE_NAME}}:latest .

  docker:run:
    desc: "Run the Docker container (usage: task docker:run PROFILE=prod)"
    requires:
      vars: [PROFILE]
    cmds:
      - docker run --rm -p 8080:8080 -e APP_PROFILE={{.PROFILE}} {{.IMAGE_NAME}}:latest

  docker:lint:
    desc: Lint the Dockerfile with hadolint
    cmds:
      - hadolint Dockerfile

  docker:dev:
    desc: Start local development server with hot reload in Docker
    cmds:
      - docker run --rm -p 8080:8080
        -v .:/src
        -v {{.IMAGE_NAME}}-gomod:/go/pkg/mod
        -v {{.IMAGE_NAME}}-gobuild:/root/.cache/go-build
        -w /src
        golang:1.25.6-alpine go tool air
