// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	ports "github.com/jsamuelsen11/go-service-template-v2/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// MockHealthRegistry is an autogenerated mock type for the HealthRegistry type
type MockHealthRegistry struct {
	mock.Mock
}

type MockHealthRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthRegistry) EXPECT() *MockHealthRegistry_Expecter {
	return &MockHealthRegistry_Expecter{mock: &_m.Mock}
}

// CheckAll provides a mock function with given fields: ctx
func (_m *MockHealthRegistry) CheckAll(ctx context.Context) map[string]error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckAll")
	}

	var r0 map[string]error
	if rf, ok := ret.Get(0).(func(context.Context) map[string]error); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]error)
		}
	}

	return r0
}

// MockHealthRegistry_CheckAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckAll'
type MockHealthRegistry_CheckAll_Call struct {
	*mock.Call
}

// CheckAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHealthRegistry_Expecter) CheckAll(ctx interface{}) *MockHealthRegistry_CheckAll_Call {
	return &MockHealthRegistry_CheckAll_Call{Call: _e.mock.On("CheckAll", ctx)}
}

func (_c *MockHealthRegistry_CheckAll_Call) Run(run func(ctx context.Context)) *MockHealthRegistry_CheckAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockHealthRegistry_CheckAll_Call) Return(_a0 map[string]error) *MockHealthRegistry_CheckAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthRegistry_CheckAll_Call) RunAndReturn(run func(context.Context) map[string]error) *MockHealthRegistry_CheckAll_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: checker
func (_m *MockHealthRegistry) Register(checker ports.HealthChecker) {
	_m.Called(checker)
}

// MockHealthRegistry_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockHealthRegistry_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - checker ports.HealthChecker
func (_e *MockHealthRegistry_Expecter) Register(checker interface{}) *MockHealthRegistry_Register_Call {
	return &MockHealthRegistry_Register_Call{Call: _e.mock.On("Register", checker)}
}

func (_c *MockHealthRegistry_Register_Call) Run(run func(checker ports.HealthChecker)) *MockHealthRegistry_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ports.HealthChecker))
	})
	return _c
}

func (_c *MockHealthRegistry_Register_Call) Return() *MockHealthRegistry_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthRegistry_Register_Call) RunAndReturn(run func(ports.HealthChecker)) *MockHealthRegistry_Register_Call {
	_c.Run(run)
	return _c
}

// NewMockHealthRegistry creates a new instance of MockHealthRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthRegistry(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockHealthRegistry {
	mock := &MockHealthRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
