// Code generated by mockery v2.53.5. DO NOT EDIT.

package ports

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockHealthChecker is an autogenerated mock type for the HealthChecker type
type MockHealthChecker struct {
	mock.Mock
}

type MockHealthChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthChecker) EXPECT() *MockHealthChecker_Expecter {
	return &MockHealthChecker_Expecter{mock: &_m.Mock}
}

// HealthCheck provides a mock function with given fields: ctx
func (_m *MockHealthChecker) HealthCheck(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHealthChecker_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type MockHealthChecker_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHealthChecker_Expecter) HealthCheck(ctx interface{}) *MockHealthChecker_HealthCheck_Call {
	return &MockHealthChecker_HealthCheck_Call{Call: _e.mock.On("HealthCheck", ctx)}
}

func (_c *MockHealthChecker_HealthCheck_Call) Run(run func(ctx context.Context)) *MockHealthChecker_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockHealthChecker_HealthCheck_Call) Return(_a0 error) *MockHealthChecker_HealthCheck_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthChecker_HealthCheck_Call) RunAndReturn(run func(context.Context) error) *MockHealthChecker_HealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockHealthChecker) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockHealthChecker_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockHealthChecker_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockHealthChecker_Expecter) Name() *MockHealthChecker_Name_Call {
	return &MockHealthChecker_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockHealthChecker_Name_Call) Run(run func()) *MockHealthChecker_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthChecker_Name_Call) Return(_a0 string) *MockHealthChecker_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthChecker_Name_Call) RunAndReturn(run func() string) *MockHealthChecker_Name_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHealthChecker creates a new instance of MockHealthChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthChecker(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockHealthChecker {
	mock := &MockHealthChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
