// Code generated by mockery v2.53.5. DO NOT EDIT.

package ports

import (
	context "context"

	domain "github.com/jsamuelsen11/go-service-template-v2/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockProjectService is an autogenerated mock type for the ProjectService type
type MockProjectService struct {
	mock.Mock
}

type MockProjectService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectService) EXPECT() *MockProjectService_Expecter {
	return &MockProjectService_Expecter{mock: &_m.Mock}
}

// AddTodo provides a mock function with given fields: ctx, projectID, todo
func (_m *MockProjectService) AddTodo(ctx context.Context, projectID int64, todo *domain.Todo) (*domain.Todo, error) {
	ret := _m.Called(ctx, projectID, todo)

	if len(ret) == 0 {
		panic("no return value specified for AddTodo")
	}

	var r0 *domain.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *domain.Todo) (*domain.Todo, error)); ok {
		return rf(ctx, projectID, todo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *domain.Todo) *domain.Todo); ok {
		r0 = rf(ctx, projectID, todo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *domain.Todo) error); ok {
		r1 = rf(ctx, projectID, todo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectService_AddTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTodo'
type MockProjectService_AddTodo_Call struct {
	*mock.Call
}

// AddTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int64
//   - todo *domain.Todo
func (_e *MockProjectService_Expecter) AddTodo(ctx interface{}, projectID interface{}, todo interface{}) *MockProjectService_AddTodo_Call {
	return &MockProjectService_AddTodo_Call{Call: _e.mock.On("AddTodo", ctx, projectID, todo)}
}

func (_c *MockProjectService_AddTodo_Call) Run(run func(ctx context.Context, projectID int64, todo *domain.Todo)) *MockProjectService_AddTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*domain.Todo))
	})
	return _c
}

func (_c *MockProjectService_AddTodo_Call) Return(_a0 *domain.Todo, _a1 error) *MockProjectService_AddTodo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectService_AddTodo_Call) RunAndReturn(run func(context.Context, int64, *domain.Todo) (*domain.Todo, error)) *MockProjectService_AddTodo_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProject provides a mock function with given fields: ctx, project
func (_m *MockProjectService) CreateProject(ctx context.Context, project *domain.Project) (*domain.Project, error) {
	ret := _m.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for CreateProject")
	}

	var r0 *domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Project) (*domain.Project, error)); ok {
		return rf(ctx, project)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Project) *domain.Project); ok {
		r0 = rf(ctx, project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Project) error); ok {
		r1 = rf(ctx, project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectService_CreateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProject'
type MockProjectService_CreateProject_Call struct {
	*mock.Call
}

// CreateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - project *domain.Project
func (_e *MockProjectService_Expecter) CreateProject(ctx interface{}, project interface{}) *MockProjectService_CreateProject_Call {
	return &MockProjectService_CreateProject_Call{Call: _e.mock.On("CreateProject", ctx, project)}
}

func (_c *MockProjectService_CreateProject_Call) Run(run func(ctx context.Context, project *domain.Project)) *MockProjectService_CreateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Project))
	})
	return _c
}

func (_c *MockProjectService_CreateProject_Call) Return(_a0 *domain.Project, _a1 error) *MockProjectService_CreateProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectService_CreateProject_Call) RunAndReturn(run func(context.Context, *domain.Project) (*domain.Project, error)) *MockProjectService_CreateProject_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProject provides a mock function with given fields: ctx, id
func (_m *MockProjectService) DeleteProject(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProjectService_DeleteProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProject'
type MockProjectService_DeleteProject_Call struct {
	*mock.Call
}

// DeleteProject is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockProjectService_Expecter) DeleteProject(ctx interface{}, id interface{}) *MockProjectService_DeleteProject_Call {
	return &MockProjectService_DeleteProject_Call{Call: _e.mock.On("DeleteProject", ctx, id)}
}

func (_c *MockProjectService_DeleteProject_Call) Run(run func(ctx context.Context, id int64)) *MockProjectService_DeleteProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockProjectService_DeleteProject_Call) Return(_a0 error) *MockProjectService_DeleteProject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProjectService_DeleteProject_Call) RunAndReturn(run func(context.Context, int64) error) *MockProjectService_DeleteProject_Call {
	_c.Call.Return(run)
	return _c
}

// GetProject provides a mock function with given fields: ctx, id
func (_m *MockProjectService) GetProject(ctx context.Context, id int64) (*domain.Project, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProject")
	}

	var r0 *domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.Project, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.Project); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectService_GetProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProject'
type MockProjectService_GetProject_Call struct {
	*mock.Call
}

// GetProject is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockProjectService_Expecter) GetProject(ctx interface{}, id interface{}) *MockProjectService_GetProject_Call {
	return &MockProjectService_GetProject_Call{Call: _e.mock.On("GetProject", ctx, id)}
}

func (_c *MockProjectService_GetProject_Call) Run(run func(ctx context.Context, id int64)) *MockProjectService_GetProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockProjectService_GetProject_Call) Return(_a0 *domain.Project, _a1 error) *MockProjectService_GetProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectService_GetProject_Call) RunAndReturn(run func(context.Context, int64) (*domain.Project, error)) *MockProjectService_GetProject_Call {
	_c.Call.Return(run)
	return _c
}

// ListProjects provides a mock function with given fields: ctx
func (_m *MockProjectService) ListProjects(ctx context.Context) ([]domain.Project, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListProjects")
	}

	var r0 []domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Project, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Project); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectService_ListProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProjects'
type MockProjectService_ListProjects_Call struct {
	*mock.Call
}

// ListProjects is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProjectService_Expecter) ListProjects(ctx interface{}) *MockProjectService_ListProjects_Call {
	return &MockProjectService_ListProjects_Call{Call: _e.mock.On("ListProjects", ctx)}
}

func (_c *MockProjectService_ListProjects_Call) Run(run func(ctx context.Context)) *MockProjectService_ListProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockProjectService_ListProjects_Call) Return(_a0 []domain.Project, _a1 error) *MockProjectService_ListProjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectService_ListProjects_Call) RunAndReturn(run func(context.Context) ([]domain.Project, error)) *MockProjectService_ListProjects_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveTodo provides a mock function with given fields: ctx, projectID, todoID
func (_m *MockProjectService) RemoveTodo(ctx context.Context, projectID int64, todoID int64) error {
	ret := _m.Called(ctx, projectID, todoID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveTodo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, projectID, todoID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProjectService_RemoveTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveTodo'
type MockProjectService_RemoveTodo_Call struct {
	*mock.Call
}

// RemoveTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int64
//   - todoID int64
func (_e *MockProjectService_Expecter) RemoveTodo(ctx interface{}, projectID interface{}, todoID interface{}) *MockProjectService_RemoveTodo_Call {
	return &MockProjectService_RemoveTodo_Call{Call: _e.mock.On("RemoveTodo", ctx, projectID, todoID)}
}

func (_c *MockProjectService_RemoveTodo_Call) Run(run func(ctx context.Context, projectID int64, todoID int64)) *MockProjectService_RemoveTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockProjectService_RemoveTodo_Call) Return(_a0 error) *MockProjectService_RemoveTodo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProjectService_RemoveTodo_Call) RunAndReturn(run func(context.Context, int64, int64) error) *MockProjectService_RemoveTodo_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProject provides a mock function with given fields: ctx, id, project
func (_m *MockProjectService) UpdateProject(ctx context.Context, id int64, project *domain.Project) (*domain.Project, error) {
	ret := _m.Called(ctx, id, project)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProject")
	}

	var r0 *domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *domain.Project) (*domain.Project, error)); ok {
		return rf(ctx, id, project)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *domain.Project) *domain.Project); ok {
		r0 = rf(ctx, id, project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *domain.Project) error); ok {
		r1 = rf(ctx, id, project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectService_UpdateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProject'
type MockProjectService_UpdateProject_Call struct {
	*mock.Call
}

// UpdateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - project *domain.Project
func (_e *MockProjectService_Expecter) UpdateProject(ctx interface{}, id interface{}, project interface{}) *MockProjectService_UpdateProject_Call {
	return &MockProjectService_UpdateProject_Call{Call: _e.mock.On("UpdateProject", ctx, id, project)}
}

func (_c *MockProjectService_UpdateProject_Call) Run(run func(ctx context.Context, id int64, project *domain.Project)) *MockProjectService_UpdateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*domain.Project))
	})
	return _c
}

func (_c *MockProjectService_UpdateProject_Call) Return(_a0 *domain.Project, _a1 error) *MockProjectService_UpdateProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectService_UpdateProject_Call) RunAndReturn(run func(context.Context, int64, *domain.Project) (*domain.Project, error)) *MockProjectService_UpdateProject_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTodo provides a mock function with given fields: ctx, projectID, todoID, todo
func (_m *MockProjectService) UpdateTodo(ctx context.Context, projectID int64, todoID int64, todo *domain.Todo) (*domain.Todo, error) {
	ret := _m.Called(ctx, projectID, todoID, todo)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTodo")
	}

	var r0 *domain.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, *domain.Todo) (*domain.Todo, error)); ok {
		return rf(ctx, projectID, todoID, todo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, *domain.Todo) *domain.Todo); ok {
		r0 = rf(ctx, projectID, todoID, todo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, *domain.Todo) error); ok {
		r1 = rf(ctx, projectID, todoID, todo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectService_UpdateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTodo'
type MockProjectService_UpdateTodo_Call struct {
	*mock.Call
}

// UpdateTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int64
//   - todoID int64
//   - todo *domain.Todo
func (_e *MockProjectService_Expecter) UpdateTodo(ctx interface{}, projectID interface{}, todoID interface{}, todo interface{}) *MockProjectService_UpdateTodo_Call {
	return &MockProjectService_UpdateTodo_Call{Call: _e.mock.On("UpdateTodo", ctx, projectID, todoID, todo)}
}

func (_c *MockProjectService_UpdateTodo_Call) Run(run func(ctx context.Context, projectID int64, todoID int64, todo *domain.Todo)) *MockProjectService_UpdateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(*domain.Todo))
	})
	return _c
}

func (_c *MockProjectService_UpdateTodo_Call) Return(_a0 *domain.Todo, _a1 error) *MockProjectService_UpdateTodo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectService_UpdateTodo_Call) RunAndReturn(run func(context.Context, int64, int64, *domain.Todo) (*domain.Todo, error)) *MockProjectService_UpdateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProjectService creates a new instance of MockProjectService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectService(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockProjectService {
	mock := &MockProjectService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
