// Code generated by mockery v2.53.5. DO NOT EDIT.

package ports

import (
	context "context"

	domain "github.com/jsamuelsen11/go-service-template-v2/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockTodoClient is an autogenerated mock type for the TodoClient type
type MockTodoClient struct {
	mock.Mock
}

type MockTodoClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTodoClient) EXPECT() *MockTodoClient_Expecter {
	return &MockTodoClient_Expecter{mock: &_m.Mock}
}

// CreateProject provides a mock function with given fields: ctx, project
func (_m *MockTodoClient) CreateProject(ctx context.Context, project *domain.Project) (*domain.Project, error) {
	ret := _m.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for CreateProject")
	}

	var r0 *domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Project) (*domain.Project, error)); ok {
		return rf(ctx, project)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Project) *domain.Project); ok {
		r0 = rf(ctx, project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Project) error); ok {
		r1 = rf(ctx, project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoClient_CreateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProject'
type MockTodoClient_CreateProject_Call struct {
	*mock.Call
}

// CreateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - project *domain.Project
func (_e *MockTodoClient_Expecter) CreateProject(ctx interface{}, project interface{}) *MockTodoClient_CreateProject_Call {
	return &MockTodoClient_CreateProject_Call{Call: _e.mock.On("CreateProject", ctx, project)}
}

func (_c *MockTodoClient_CreateProject_Call) Run(run func(ctx context.Context, project *domain.Project)) *MockTodoClient_CreateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Project))
	})
	return _c
}

func (_c *MockTodoClient_CreateProject_Call) Return(_a0 *domain.Project, _a1 error) *MockTodoClient_CreateProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoClient_CreateProject_Call) RunAndReturn(run func(context.Context, *domain.Project) (*domain.Project, error)) *MockTodoClient_CreateProject_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTodo provides a mock function with given fields: ctx, todo
func (_m *MockTodoClient) CreateTodo(ctx context.Context, todo *domain.Todo) (*domain.Todo, error) {
	ret := _m.Called(ctx, todo)

	if len(ret) == 0 {
		panic("no return value specified for CreateTodo")
	}

	var r0 *domain.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Todo) (*domain.Todo, error)); ok {
		return rf(ctx, todo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Todo) *domain.Todo); ok {
		r0 = rf(ctx, todo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Todo) error); ok {
		r1 = rf(ctx, todo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoClient_CreateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTodo'
type MockTodoClient_CreateTodo_Call struct {
	*mock.Call
}

// CreateTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - todo *domain.Todo
func (_e *MockTodoClient_Expecter) CreateTodo(ctx interface{}, todo interface{}) *MockTodoClient_CreateTodo_Call {
	return &MockTodoClient_CreateTodo_Call{Call: _e.mock.On("CreateTodo", ctx, todo)}
}

func (_c *MockTodoClient_CreateTodo_Call) Run(run func(ctx context.Context, todo *domain.Todo)) *MockTodoClient_CreateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Todo))
	})
	return _c
}

func (_c *MockTodoClient_CreateTodo_Call) Return(_a0 *domain.Todo, _a1 error) *MockTodoClient_CreateTodo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoClient_CreateTodo_Call) RunAndReturn(run func(context.Context, *domain.Todo) (*domain.Todo, error)) *MockTodoClient_CreateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProject provides a mock function with given fields: ctx, id
func (_m *MockTodoClient) DeleteProject(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTodoClient_DeleteProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProject'
type MockTodoClient_DeleteProject_Call struct {
	*mock.Call
}

// DeleteProject is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockTodoClient_Expecter) DeleteProject(ctx interface{}, id interface{}) *MockTodoClient_DeleteProject_Call {
	return &MockTodoClient_DeleteProject_Call{Call: _e.mock.On("DeleteProject", ctx, id)}
}

func (_c *MockTodoClient_DeleteProject_Call) Run(run func(ctx context.Context, id int64)) *MockTodoClient_DeleteProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockTodoClient_DeleteProject_Call) Return(_a0 error) *MockTodoClient_DeleteProject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTodoClient_DeleteProject_Call) RunAndReturn(run func(context.Context, int64) error) *MockTodoClient_DeleteProject_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTodo provides a mock function with given fields: ctx, id
func (_m *MockTodoClient) DeleteTodo(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTodo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTodoClient_DeleteTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTodo'
type MockTodoClient_DeleteTodo_Call struct {
	*mock.Call
}

// DeleteTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockTodoClient_Expecter) DeleteTodo(ctx interface{}, id interface{}) *MockTodoClient_DeleteTodo_Call {
	return &MockTodoClient_DeleteTodo_Call{Call: _e.mock.On("DeleteTodo", ctx, id)}
}

func (_c *MockTodoClient_DeleteTodo_Call) Run(run func(ctx context.Context, id int64)) *MockTodoClient_DeleteTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockTodoClient_DeleteTodo_Call) Return(_a0 error) *MockTodoClient_DeleteTodo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTodoClient_DeleteTodo_Call) RunAndReturn(run func(context.Context, int64) error) *MockTodoClient_DeleteTodo_Call {
	_c.Call.Return(run)
	return _c
}

// GetProject provides a mock function with given fields: ctx, id
func (_m *MockTodoClient) GetProject(ctx context.Context, id int64) (*domain.Project, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProject")
	}

	var r0 *domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.Project, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.Project); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoClient_GetProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProject'
type MockTodoClient_GetProject_Call struct {
	*mock.Call
}

// GetProject is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockTodoClient_Expecter) GetProject(ctx interface{}, id interface{}) *MockTodoClient_GetProject_Call {
	return &MockTodoClient_GetProject_Call{Call: _e.mock.On("GetProject", ctx, id)}
}

func (_c *MockTodoClient_GetProject_Call) Run(run func(ctx context.Context, id int64)) *MockTodoClient_GetProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockTodoClient_GetProject_Call) Return(_a0 *domain.Project, _a1 error) *MockTodoClient_GetProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoClient_GetProject_Call) RunAndReturn(run func(context.Context, int64) (*domain.Project, error)) *MockTodoClient_GetProject_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectTodos provides a mock function with given fields: ctx, projectID, filter
func (_m *MockTodoClient) GetProjectTodos(ctx context.Context, projectID int64, filter domain.TodoFilter) ([]domain.Todo, error) {
	ret := _m.Called(ctx, projectID, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectTodos")
	}

	var r0 []domain.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.TodoFilter) ([]domain.Todo, error)); ok {
		return rf(ctx, projectID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.TodoFilter) []domain.Todo); ok {
		r0 = rf(ctx, projectID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, domain.TodoFilter) error); ok {
		r1 = rf(ctx, projectID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoClient_GetProjectTodos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectTodos'
type MockTodoClient_GetProjectTodos_Call struct {
	*mock.Call
}

// GetProjectTodos is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int64
//   - filter domain.TodoFilter
func (_e *MockTodoClient_Expecter) GetProjectTodos(ctx interface{}, projectID interface{}, filter interface{}) *MockTodoClient_GetProjectTodos_Call {
	return &MockTodoClient_GetProjectTodos_Call{Call: _e.mock.On("GetProjectTodos", ctx, projectID, filter)}
}

func (_c *MockTodoClient_GetProjectTodos_Call) Run(run func(ctx context.Context, projectID int64, filter domain.TodoFilter)) *MockTodoClient_GetProjectTodos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(domain.TodoFilter))
	})
	return _c
}

func (_c *MockTodoClient_GetProjectTodos_Call) Return(_a0 []domain.Todo, _a1 error) *MockTodoClient_GetProjectTodos_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoClient_GetProjectTodos_Call) RunAndReturn(run func(context.Context, int64, domain.TodoFilter) ([]domain.Todo, error)) *MockTodoClient_GetProjectTodos_Call {
	_c.Call.Return(run)
	return _c
}

// GetTodo provides a mock function with given fields: ctx, id
func (_m *MockTodoClient) GetTodo(ctx context.Context, id int64) (*domain.Todo, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTodo")
	}

	var r0 *domain.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.Todo, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.Todo); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoClient_GetTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTodo'
type MockTodoClient_GetTodo_Call struct {
	*mock.Call
}

// GetTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockTodoClient_Expecter) GetTodo(ctx interface{}, id interface{}) *MockTodoClient_GetTodo_Call {
	return &MockTodoClient_GetTodo_Call{Call: _e.mock.On("GetTodo", ctx, id)}
}

func (_c *MockTodoClient_GetTodo_Call) Run(run func(ctx context.Context, id int64)) *MockTodoClient_GetTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockTodoClient_GetTodo_Call) Return(_a0 *domain.Todo, _a1 error) *MockTodoClient_GetTodo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoClient_GetTodo_Call) RunAndReturn(run func(context.Context, int64) (*domain.Todo, error)) *MockTodoClient_GetTodo_Call {
	_c.Call.Return(run)
	return _c
}

// ListProjects provides a mock function with given fields: ctx
func (_m *MockTodoClient) ListProjects(ctx context.Context) ([]domain.Project, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListProjects")
	}

	var r0 []domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Project, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Project); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoClient_ListProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProjects'
type MockTodoClient_ListProjects_Call struct {
	*mock.Call
}

// ListProjects is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTodoClient_Expecter) ListProjects(ctx interface{}) *MockTodoClient_ListProjects_Call {
	return &MockTodoClient_ListProjects_Call{Call: _e.mock.On("ListProjects", ctx)}
}

func (_c *MockTodoClient_ListProjects_Call) Run(run func(ctx context.Context)) *MockTodoClient_ListProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTodoClient_ListProjects_Call) Return(_a0 []domain.Project, _a1 error) *MockTodoClient_ListProjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoClient_ListProjects_Call) RunAndReturn(run func(context.Context) ([]domain.Project, error)) *MockTodoClient_ListProjects_Call {
	_c.Call.Return(run)
	return _c
}

// ListTodos provides a mock function with given fields: ctx, filter
func (_m *MockTodoClient) ListTodos(ctx context.Context, filter domain.TodoFilter) ([]domain.Todo, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListTodos")
	}

	var r0 []domain.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TodoFilter) ([]domain.Todo, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.TodoFilter) []domain.Todo); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.TodoFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoClient_ListTodos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTodos'
type MockTodoClient_ListTodos_Call struct {
	*mock.Call
}

// ListTodos is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.TodoFilter
func (_e *MockTodoClient_Expecter) ListTodos(ctx interface{}, filter interface{}) *MockTodoClient_ListTodos_Call {
	return &MockTodoClient_ListTodos_Call{Call: _e.mock.On("ListTodos", ctx, filter)}
}

func (_c *MockTodoClient_ListTodos_Call) Run(run func(ctx context.Context, filter domain.TodoFilter)) *MockTodoClient_ListTodos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TodoFilter))
	})
	return _c
}

func (_c *MockTodoClient_ListTodos_Call) Return(_a0 []domain.Todo, _a1 error) *MockTodoClient_ListTodos_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoClient_ListTodos_Call) RunAndReturn(run func(context.Context, domain.TodoFilter) ([]domain.Todo, error)) *MockTodoClient_ListTodos_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProject provides a mock function with given fields: ctx, id, project
func (_m *MockTodoClient) UpdateProject(ctx context.Context, id int64, project *domain.Project) (*domain.Project, error) {
	ret := _m.Called(ctx, id, project)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProject")
	}

	var r0 *domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *domain.Project) (*domain.Project, error)); ok {
		return rf(ctx, id, project)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *domain.Project) *domain.Project); ok {
		r0 = rf(ctx, id, project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *domain.Project) error); ok {
		r1 = rf(ctx, id, project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoClient_UpdateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProject'
type MockTodoClient_UpdateProject_Call struct {
	*mock.Call
}

// UpdateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - project *domain.Project
func (_e *MockTodoClient_Expecter) UpdateProject(ctx interface{}, id interface{}, project interface{}) *MockTodoClient_UpdateProject_Call {
	return &MockTodoClient_UpdateProject_Call{Call: _e.mock.On("UpdateProject", ctx, id, project)}
}

func (_c *MockTodoClient_UpdateProject_Call) Run(run func(ctx context.Context, id int64, project *domain.Project)) *MockTodoClient_UpdateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*domain.Project))
	})
	return _c
}

func (_c *MockTodoClient_UpdateProject_Call) Return(_a0 *domain.Project, _a1 error) *MockTodoClient_UpdateProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoClient_UpdateProject_Call) RunAndReturn(run func(context.Context, int64, *domain.Project) (*domain.Project, error)) *MockTodoClient_UpdateProject_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTodo provides a mock function with given fields: ctx, id, todo
func (_m *MockTodoClient) UpdateTodo(ctx context.Context, id int64, todo *domain.Todo) (*domain.Todo, error) {
	ret := _m.Called(ctx, id, todo)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTodo")
	}

	var r0 *domain.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *domain.Todo) (*domain.Todo, error)); ok {
		return rf(ctx, id, todo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *domain.Todo) *domain.Todo); ok {
		r0 = rf(ctx, id, todo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *domain.Todo) error); ok {
		r1 = rf(ctx, id, todo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoClient_UpdateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTodo'
type MockTodoClient_UpdateTodo_Call struct {
	*mock.Call
}

// UpdateTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - todo *domain.Todo
func (_e *MockTodoClient_Expecter) UpdateTodo(ctx interface{}, id interface{}, todo interface{}) *MockTodoClient_UpdateTodo_Call {
	return &MockTodoClient_UpdateTodo_Call{Call: _e.mock.On("UpdateTodo", ctx, id, todo)}
}

func (_c *MockTodoClient_UpdateTodo_Call) Run(run func(ctx context.Context, id int64, todo *domain.Todo)) *MockTodoClient_UpdateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*domain.Todo))
	})
	return _c
}

func (_c *MockTodoClient_UpdateTodo_Call) Return(_a0 *domain.Todo, _a1 error) *MockTodoClient_UpdateTodo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoClient_UpdateTodo_Call) RunAndReturn(run func(context.Context, int64, *domain.Todo) (*domain.Todo, error)) *MockTodoClient_UpdateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTodoClient creates a new instance of MockTodoClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTodoClient(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockTodoClient {
	mock := &MockTodoClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
